services:
  # Frontend
  frontend:
    image: frontend:latest
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./dist/:/var/site/
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 3000:80

  # Backend
  backend:
    image: backend:latest
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ${PWD}:/app/
    command: "flask --app src/backend/main.py run --debug --port 5000 --host 0.0.0.0"
    ports:
      - 5000:5000
